<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="110400" started-at="2020-05-23T14:14:02 IDT" finished-at="2020-05-23T14:15:53 IDT">
    <groups>
    </groups>
    <test name="Mobile Test" duration-ms="110400" started-at="2020-05-23T14:14:02 IDT" finished-at="2020-05-23T14:15:53 IDT">
      <class name="SanityTests.experiBankMobile">
        <test-method status="PASS" signature="startSession()[pri:0, instance:SanityTests.experiBankMobile@7dac3fd8]" name="startSession" is-config="true" duration-ms="13684" started-at="2020-05-23T14:14:02 IDT" finished-at="2020-05-23T14:14:16 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method status="PASS" signature="login()[pri:1, instance:SanityTests.experiBankMobile@7dac3fd8]" name="login" duration-ms="4532" started-at="2020-05-23T14:14:16 IDT" description="Login" finished-at="2020-05-23T14:14:21 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="makeOnePayment()[pri:2, instance:SanityTests.experiBankMobile@7dac3fd8]" name="makeOnePayment" duration-ms="20366" started-at="2020-05-23T14:14:21 IDT" description="Send Payment" finished-at="2020-05-23T14:14:41 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeOnePayment -->
        <test-method status="PASS" signature="takeMortgage()[pri:3, instance:SanityTests.experiBankMobile@7dac3fd8]" name="takeMortgage" duration-ms="66957" started-at="2020-05-23T14:14:41 IDT" description="Take Mortgage Request" finished-at="2020-05-23T14:15:48 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeMortgage -->
        <test-method status="FAIL" signature="error()[pri:4, instance:SanityTests.experiBankMobile@7dac3fd8]" name="error" duration-ms="375" started-at="2020-05-23T14:15:48 IDT" description="ERROR" finished-at="2020-05-23T14:15:49 IDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100.00$] but found [Your balance is: 75.00$]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100.00$] but found [Your balance is: 75.00$]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Extensions.verifications.assertTextInElement(verifications.java:41)
at SanityTests.experiBankMobile.error(experiBankMobile.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- error -->
        <test-method status="PASS" signature="closeSession()[pri:0, instance:SanityTests.experiBankMobile@7dac3fd8]" name="closeSession" is-config="true" duration-ms="3657" started-at="2020-05-23T14:15:49 IDT" finished-at="2020-05-23T14:15:53 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSession -->
      </class> <!-- SanityTests.experiBankMobile -->
    </test> <!-- Mobile Test -->
  </suite> <!-- Suite -->
</testng-results>
